// const cssIconList = ['arrow-down', 'arrow-left', 'arrow-right', 'arrow-up', 'audio', 'audio-solid', 'battery', 'battery-0', 'battery-1', 'battery-3', 'battery-solid', 'battery-solid-0', 'battery-solid-1', 'battery-solid-3', 'bell', 'bell-solid', 'bookmark', 'bookmark-solid', 'browser', 'browser-solid', 'C', 'camera', 'camera-solid', 'card', 'card-solid', 'center-align', 'chat', 'chat-solid', 'check', 'clock', 'clock-h3m30', 'clock-h3m30-solid', 'clock-h9m0', 'clock-h9m0-solid', 'clock-h9m30', 'clock-h9m30-solid', 'clock-solid', 'close', 'cloud', 'cloud-download', 'cloud-download-solid', 'cloud-lightning', 'cloud-raindrop', 'cloud-solid', 'cloud-upload', 'cloud-upload-solid', 'code', 'download', 'edit', 'edit-solid', 'export', 'eye', 'eye-solid', 'eye-solid2', 'eye-solid3', 'flag', 'flag-solid', 'float', 'float-solid', 'focus', 'grin', 'grin-solid', 'grin-wink', 'heart', 'heart-solid', 'I', 'import', 'indent', 'justified', 'key', 'key-solid', 'key2', 'key2-solid', 'keyboard', 'keyboard-solid', 'laptop', 'laptop-solid', 'laugh', 'laugh-solid', 'left-align', 'left-double-quote', 'left-double-quote-solid', 'left-single-quote', 'left-single-quote-solid', 'link', 'lock', 'lock-solid', 'magnify', 'magnify-solid', 'mail', 'mail-solid', 'map', 'menu', 'minify', 'minify-solid', 'minus', 'mobile', 'mobile-solid', 'moon', 'moon-solid', 'more', 'more-solid', 'more-vertical', 'more-vertical-solid', 'mouse', 'mouse-solid', 'mustache', 'mustache-solid', 'N', 'navigate', 'navigate-solid', 'no-raindrop', 'O', 'outdent', 'paperclip', 'paragraph-direction', 'pensive', 'pensive-solid', 'picture', 'picture-solid', 'pilcrow', 'pilcrow-solid', 'pin', 'pin-solid', 'plus', 'print', 'print-solid', 'profile', 'profile-solid', 'rain', 'raindrop', 'raindrop-solid', 'refresh', 'relieved', 'relieved-smiley', 'relieved-smiley-solid', 'relieved-solid', 'remove', 'retweet', 'right-align', 'right-double-quote', 'right-double-quote-solid', 'right-single-quote', 'right-single-quote-solid', 'S', 'sad', 'sad-solid', 'search', 'search-solid', 'shutdown', 'signal', 'smile', 'smile-solid', 'smiley', 'smiley-solid', 'snow', 'stop', 'stop-solid', 'suitcase', 'suitcase-1', 'suitcase-2', 'suitcase-3', 'sun', 'sun-brightness', 'sun-horizon', 'sun-horizon-solid', 'sun-raindrop', 'sun-raindrop-solid', 'sun-solid', 'sunrise', 'sunrise-solid', 'sunset', 'sunset-solid', 'tablet', 'tablet-solid', 'tag', 'tag-solid', 'target', 'target-solid', 'template-i-before-after', 'tougue', 'tougue-solid', 'trash', 'trash-solid', 'tv', 'tv-solid', 'unamused', 'unamused-solid', 'unlock', 'unlock-solid', 'upload', 'upload2', 'watch', 'watch-solid', 'wink', 'wink-laugh', 'wink-smiley', 'wink-tougue', 'ls', 'template-before-after.zip', 'template-before.zip', 'template-i-before-after.zip', 'template-i.zip', 'template-main.zip'];

// const iconoList = ['arrow', 'asterisk', 'bars', 'bluetooth', 'book', 'bookmark', 'calendar', 'camera', 'caret', 'cart', 'chain', 'chart', 'check', 'circle', 'clock', 'comment', 'creditCard', 'crop', 'cross', 'cup', 'display', 'document', 'dropper', 'ellipsis', 'exclamation', 'eye', 'file', 'filter', 'flag', 'folder', 'forbidden', 'forward', 'frown', 'gear', 'headphone', 'heart', 'home', 'icono', 'imac', 'image', 'indent', 'infinity', 'iphone', 'keyboard', 'list', 'locationArrow', 'macbook', 'mail', 'market', 'meh', 'microphone', 'moon', 'mouse', 'music', 'next', 'nexus', 'outdent', 'paperclip', 'pause', 'piano', 'pin', 'play', 'plus', 'power', 'previous', 'rename', 'reset', 'rewind', 'rss', 'ruler', 'search', 'share', 'signin', 'signout', 'sitemap', 'sliders', 'smile', 'socials', 'spinner', 'stop', 'sun', 'support', 'sync', 'tag', 'terminal', 'textAlign', 'tiles', 'trash', 'user', 'video', 'volume', 'youtube'];


// load css
// parse
// find & group
// generate data
